# Generated by Django 3.2.16 on 2022-12-12 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NowPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.IntegerField(choices=[(0, 'a christmas carol'), (1, 'phantom of the opera')])),
                ('status', models.IntegerField(choices=[(0, 'available'), (1, 'booked')], default=0)),
                ('seats', models.IntegerField(verbose_name=41)),
                ('date', models.IntegerField(choices=[(0, '10/12'), (1, '13/12'), (2, '17/12'), (3, '20/12'), (4, '23/12')])),
                ('time', models.IntegerField(choices=[(0, '12:30'), (1, '16:00')])),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.IntegerField(choices=[(0, 'a christmas carol'), (1, 'phantom of the opera')])),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'available'), (1, 'booked')], default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.nowplaying')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
