# Generated by Django 3.2.16 on 2023-01-18 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(default='To be added', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NowPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'available'), (1, 'booked')], default=0)),
                ('seats', models.IntegerField(verbose_name=41)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.play')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.nowplaying')),
            ],
            options={
                'ordering': ['-playing'],
            },
        ),
    ]
