# Generated by Django 3.2.16 on 2023-01-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(default='To be added', max_length=1000)),
                ('image', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NowPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'available'), (1, 'booked')], default=0)),
                ('seats', models.IntegerField(default=41)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.play')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
