# Generated by Django 3.2.16 on 2023-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nowplaying',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
