# Generated by Django 3.2.16 on 2023-01-26 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.nowplaying')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.play')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='useraccount.userprofile')),
            ],
            options={
                'ordering': ['play'],
            },
        ),
    ]
