# Generated by Django 3.2.16 on 2022-11-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.IntegerField(choices=[(0, 'a christmas carol'), (1, 'phantom of the opera')])),
                ('status', models.IntegerField(choices=[(0, 'available'), (1, 'booked')], default=0)),
                ('seats', models.IntegerField(verbose_name=41)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.DeleteModel(
            name='Now_playing',
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
