# Generated by Django 3.2.16 on 2022-11-27 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_alter_booking_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-time']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.nowplaying'),
        ),
    ]
