# Generated by Django 3.2.16 on 2022-11-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20221127_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowplaying',
            name='date',
            field=models.IntegerField(choices=[(0, '10/12'), (1, '13/12'), (2, '17/12'), (3, '20/12'), (4, '23/12')]),
        ),
        migrations.AlterField(
            model_name='nowplaying',
            name='time',
            field=models.IntegerField(choices=[(0, '12:30'), (1, '16:00')]),
        ),
    ]
