# Generated by Django 3.2.16 on 2022-11-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20221127_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
